require: rubocop-rspec

Metrics/AbcSize:
  Enabled: no

Metrics/BlockLength:
  Enabled: no

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: no

Style/Documentation:
  Enabled: no

RSpec/ExampleLength:
  Enabled: no

RSpec/MultipleExpectations:
  Enabled: no

Style/FrozenStringLiteralComment:
  Enabled: yes
  EnforcedStyle: always
  Include:
    - 'lib/**/*'

Metrics/CyclomaticComplexity:
  Max: 7

Style/RedundantFreeze:
  Enabled: no # TODO: reenable

Style/SafeNavigation:
  Enabled: no # TODO: reenable

Gemspec/RequiredRubyVersion:
  Enabled: no # doesn't apply because we're a library

RSpec/MultipleMemoizedHelpers:
  Enabled: no # TODO: reenable

Lint/ConstantDefinitionInBlock:
  Enabled: no # TODO: reenable

RSpec/LeakyConstantDeclaration:
  Enabled: no # TODO: reenable

Style/StringConcatenation:
  Enabled: no # TODO: reenable

Style/StringLiterals:
  Exclude:
    - 'gemfiles/**/*'
