name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
permissions: read-all

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    permissions: read-all
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.2.10', '2.5.9', '2.6.7', '2.7.4', '3.0.2']
        rack: ['2.2', '2.1', '2.0', '1.6']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Fix rubygems/bundler # fixes https://github.com/rubygems/rubygems/issues/3284
        if: ${{ matrix.ruby != '2.2.10' }}
        run: gem update --system
      - name: Install dependencies
        run: bundle install
      - name: Install appraisal dependencies
        run: bundle exec appraisal install
      - name: Test
        run: bundle exec appraisal rack-${{ matrix.rack }} rake spec

  # lint:
  #   if: ${{ github.event_name == 'pull_request' }}
  #   runs-on: ubuntu-latest
  #   permissions: read-all
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: '3.0'
  #         bundler-cache: true # runs 'bundle install' and caches installed gems automatically
  #     - name: Test
  #       run: bundle exec rake rubocop
